### ISSUE TITLE
Why does cracks prevent a major release?

### ISSUE THREAD

**Issue by gr2m** [semantic-release/cracks#4] opened 2015-11-08 22:26 UTC
see https://travis-ci.org/hoodiehq/hoodie-zuul-config/builds/89995618

Any idea?

**Comment by gr2m** [comment] 2015-11-08 22:29
oh, is it possible that `BREAKING CHANGE:` must not appear on first line?
https://github.com/hoodiehq/hoodie-zuul-config/commit/f4f0e3dd8ce2eb5d9452aafb4c315afd97f372f7

**Comment by davidpfahler** [comment] 2016-05-26 12:43
@gr2m I think cracks didn't prevent a release here, but semantic-release failed to detect the new version, because breaking changes are [supposed to be described in the commit message footer](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.gbbngquhe0qa). 

I think this is in fact expected behavior, as cracks detecting a breaking change should not overwrite broken commit message syntax. I would think otherwise if you had disabled commit message conventions completely for semantic release and relied solely on cracks to determine the version number (whether or not that should be possible is another question).

I suggest closing this issue,

**Closed as completed** 2016-05-29 19:46 UTC
